### ISSUE TITLE
scheduler caught exception: undefined method `gsub' for nil:NilClass 

### ISSUE THREAD

**Issue by AndrejScak** [acockburn/hadashboard#10]
Hi!
I get this error when starting dashing. Could you please help?

Thin web server (v1.6.4 codename Gob Bluth)
Maximum connections set to 1024
Listening on 0.0.0.0:3030, CTRL+C to stop

scheduler caught exception:
undefined method `gsub' for nil:NilClass
/home/pi/hadashboard/jobs/homeassistant.rb:234:in`block in <top (required)>'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in`trigger_block'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in`call'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'

**Comment by acockburn** [comment]
Do you have `weather_icon` included in your forecast.io configuration in Home Assistant? e,g,:

```
monitored_conditions:
    ....
    - icon
    ...
```

**Comment by AndrejScak** [comment]
I have activated Forecast.io component in Home Assistant and now there is no errors. Thanks
