### ISSUE TITLE
Problem with Docker instructions for Raspberry Pi

### ISSUE THREAD

**Issue by rogersmj** [acockburn/hadashboard#14]
I've been trying to get this running on a Raspberry Pi using Docker. I'm on an RPi3 with Jessie Lite.

I installed Docker using the officially provided Raspbian packages, with `apt-get install docker docker.io`. Everything seemed to go fine.

But when I attempt to run the command specified in your instructions for the RPi, I get the following:

```
$ docker build -f Docker-raspi/Dockerfile -t hadashboard .
flag provided but not defined: -f

Usage: docker build [OPTIONS] PATH | URL | -

Build a new image from the source code at PATH

  --force-rm=false     Always remove intermediate containers, even after unsuccessful builds
  --no-cache=false     Do not use cache when building the image
  -q, --quiet=false    Suppress the verbose output generated by the containers
  --rm=true            Remove intermediate containers after a successful build
  -t, --tag=""         Repository name (and optionally a tag) to be applied to the resulting image in case of success
```

It seems that the "-f" flag isn't recognized. What is that flag supposed to do? Any ideas why my system wouldn't recognize it?

Looks like I have Docker version 1.3.3, build d344625.

**Comment by rogersmj** [comment]
@snizzleorg Since you contributed the RPi instructions for this project, would you mind taking a look at my question?

**Comment by acockburn** [comment]
It is meant to point to the path of the docker file (DDocker-raspi/Dockerfile):

```
Usage: docker build [OPTIONS] PATH | URL | -

Build a new image from the source code at PATH

  -f, --file=""            Name of the Dockerfile (Default is 'PATH/Dockerfile')
...
```

I have no idea why it wouldn;t work for you, it is a standard parameter. You could try overwriting the file `Docker` in the main directory with the one in `Docker-raspi` then running it without `-f` and the Dockerfile path:

```
$ docker build -t hadashboard .
```

**Comment by rogersmj** [comment]
Thanks, I'll try that. It looks like I'm running a really ancient version of Docker which doesn't support that -f option. 

I have been unsuccessful in getting a more recent version of Docker running, it says my kernel isn't compatible (requires AUFS, and I also can't seem to get a virtual kernel installed). Other than running the Home Assistant installer, this is a pretty vanilla install of Jessie Lite. I'm not sure why I'm running into so many issues.

**Comment by acockburn** [comment]
Makes sense - I had the impression that the Docker support on Pi wasn't as good as it should be. FWIW, I did test it so it should be possible, I was running Raspian full and as far as I remember I just used apt-get to install Docker.

**Comment by rogersmj** [comment]
I finally got a new version of Docker working with my RPi and the command in the instructions worked for me. I had to use one provided from a Hypriot package server rather than Raspian. Closing.

**Comment by snizzleorg** [comment]
the hypriot version is the one I used as well.
