### ISSUE TITLE
hameter values don't update..

### ISSUE THREAD

**Issue by joyrider3774** [acockburn/hadashboard#25]
Hi,

i just noticed this .. the hameter widget values don't update, i think the reason is a missing mapping between hameter and sensor. if i add "Hameter": "sensor" to translateview [here](https://github.com/home-assistant/hadashboard/blob/master/hapush/hapush.py#L158) it does update.. i'm guessing it's missing ?

**Comment by acockburn** [comment]
I ran a quick test and Hameter works fine for me - if it isn't working there may be something else going on. You are right though, Hameter should have been mapped there but only for completeness, as that mapping is only actually used for input_select at the moment.
