### ISSUE TITLE
Add CSS to allow the whole widget to be targeted for 'active' and 'inactive' states

### ISSUE THREAD

**Issue by rogersmj** [acockburn/hadashboard#27]
Idea: Update widgets so that their top-level containers will have 'active' or 'inactive' class, if applicable, so that custom CSS can be used to easily change the background color (or text color, or anything else inside it) of a widget depending on state.

For example, a user might want to have the option to have an entire tile light up red when a door is open, instead of just the icon changing color.

Need to think about the most extensible way to do this -- can it be done in a more DRY way than updating every widget's coffee file with CSS manipulation?

EDIT: I'm dropping this here because there's no "Projects" spot for this repo. Let me know if you have a preferred way of managing backlog ideas.

**Comment by acockburn** [comment]
I like the idea - I can see I am going to have to get up to speed on CSS a little more to keep up :)

I am planning to dig into your CSS changes tomorrow to see how you went about with the refactoring and give it a test run - hopefully after I see how it all hangs together I'll have some inspiration on how to think more about this.

From my attempts to change foreground colors I ran into issues when trying to pass them through as parameters in the dashboard itself, The approach that worked for the background color failes for foreground as the coffeescript piece doesn't seem to have a way to change specific styles, and I can now see the advantages of doing that in CSS.

I think however, changing the whole tile might run into the same issue as it will have to be done dynamically.

**Comment by acockburn** [comment]
I'll take a look at adding this to HADashboard v2.

**Comment by acockburn** [comment]
I have this on my list - closing this Issue as it will apply to the AppDaemon repo when HADasboard v2 is released.
