### ISSUE TITLE
Clarification of Pi instructions please

### ISSUE THREAD

**Issue by xbmcnut** [acockburn/hadashboard#29]
Hi,

Wondering if you can confirm my steps on Jessie?
`git clone https://github.com/home-assistant/hadashboard.git`
`cd hadashboard`
`docker build -f Docker-raspi/Dockerfile -t hadashboard .` (took 5hrs on PiB with no errrors)

Copied the ha_conf.rb.example file to ha_conf.rb and edit settings
Copied dashboards/example.erb and called it 'main.erb'

`docker run --name="hadashboard" -d -v /home/pi/hadashboard/dashboards:/app/dashboards -v /home/pi/hadashboard/lib/ha_conf.rb:/app/lib/ha_conf.rb -v /home/pi/hadashboard/hapush:/app/hapush --net=host hadashboard`

Last line returns `0aac704f2093dd10ff0413f0e77c50769c5c569ee25fd57cb67ee1d338e51f3b` so assume containing is running.

And then this is what I get:

```
pi@raspberrypi:~ $ cd hadashboard
pi@raspberrypi:~/hadashboard $ dashing start                                    
-bash: dashing: command not found
pi@raspberrypi:~/hadashboard $
```

How do I debug that? Is there a problem with my paths in my docker run command?

**Comment by snizzleorg** [comment]
this is not surprising. since hadashing will run **inside** the container. (its  a bit like a virtual machine) so your host (the one where you run the commands on) will not know anything about hadashboard. Hadashboard should be available via the usual port. you can check if the container is running correctly by running 

```
docker ps -a
```

which shows the running containers

the logs you get via

```
docker logs xxxxxxx
```

where the xxxxxxx you have to replace with the container id you get from the previous command.

**Comment by xbmcnut** [comment]
Ah of course! Here we go.

```
pi@raspberrypi:~ $ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS               NAMES
0aac704f2093        hadashboard         "/bin/sh -c '/app/hap"   27 minutes ago      Exited (1) 27 minutes ago                       hadashboard
pi@raspberrypi:~ $ docker logs 0aac704f2093
Traceback (most recent call last):
  File "/app/hapush/hapush.py", line 348, in <module>
    main()
  File "/app/hapush/hapush.py", line 299, in main
    config = ConfigObj(config_file, file_error=True)
  File "/usr/local/lib/python3.4/dist-packages/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/usr/local/lib/python3.4/dist-packages/configobj.py", line 1240, in _load
    raise IOError('Config file not found: "%s".' % self.filename)
OSError: Config file not found: "/app/hapush/hapush.cfg".
```

**Comment by snizzleorg** [comment]
alright so you are missing `hapush.cfg`  which based on your docker run command should be here:

```
/home/pi/hadashboard/hapush
```

after you sorted that restart the container with

```
docker restart 0aac704f2093
```

explanation:
- v maps different filesystem locations from the host into the container:

```
-v /home/pi/hadashboard/dashboards:/app/dashboards 
```

means:

`/home/pi/hadashboard/dashboards`on the host will be `/app/dashboards` in the container

**Comment by xbmcnut** [comment]
Yep, see that now, thanks. Is this right for my install?

```
ha_url = "http://10.0.2.17:8123"
ha_key = 
dash_host = "10.0.2.17:3030"
dash_dir = "/srv/hass/src/hadashboard/dashboards"
logfile = "/etc/hapush/hapush.log"
```

Do I need to edit dash_dir and logfile? If correct, how do I restart container?

**Comment by snizzleorg** [comment]
again according to your docker run command

```
dash_dir="/app/dashboards"
```

i guess the log files you can leave in `/etc/hapush` but if you want to easily access them you should put them into `/app/hapush` which will be `/home/pi/hadashboard/hapush`on the host.

**Comment by xbmcnut** [comment]
Thank you, I appreciate the quick reply. Can I restart the container somehow or should I just reboot?

**Comment by snizzleorg** [comment]
```
docker restart 0aac704f2093
```

after a reboot the container will not start automatically unless you specify that explicitly (which is a docker run option)

**Comment by snizzleorg** [comment]
I personally prefer docker-compose to create and runt the images:
this is my docker-compose.yaml file for hadashboard:

``` yaml
---
home-assistant:
  build: Dockerfile-rpi
  restart: always
  net: "host"
  volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - '/etc/timezone:/etc/timezone:ro'
    - '/etc/home-assistant/hadashboard/dashboards:/app/dashboards
    - '/etc/home-assistant/hadashboard/config/:/app/lib/
    - '/etc/home-assistant/hadashboard/hapush/:/app/hapush/
```

Th restart alway option automatically (re)starts the container if it crashes or the host reboots.

**Comment by xbmcnut** [comment]
That's a little beyond my expertise for now. Now I'm getting this:

```
pi@raspberrypi:~ $ docker logs 0aac704f2093
Traceback (most recent call last):
  File "/app/hapush/hapush.py", line 348, in <module>
    main()
  File "/app/hapush/hapush.py", line 299, in main
    config = ConfigObj(config_file, file_error=True)
  File "/usr/local/lib/python3.4/dist-packages/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/usr/local/lib/python3.4/dist-packages/configobj.py", line 1240, in _load
    raise IOError('Config file not found: "%s".' % self.filename)
OSError: Config file not found: "/app/hapush/hapush.cfg".
================================================================================
scheduler caught exception:
undefined method `strip' for #<Hash:0x80fbbba0>
/usr/local/lib/ruby/2.2.0/net/http/header.rb:17:in `block in initialize_http_header'
/usr/local/lib/ruby/2.2.0/net/http/header.rb:15:in `each'
/usr/local/lib/ruby/2.2.0/net/http/header.rb:15:in `initialize_http_header'
/app/jobs/homeassistant.rb:22:in `ha_api'
/app/jobs/homeassistant.rb:282:in `block in <top (required)>'
/usr/local/bundle/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/usr/local/bundle/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/usr/local/bundle/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/usr/local/bundle/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `call'
/usr/local/bundle/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
================================================================================
```

**Comment by xbmcnut** [comment]
Here is the modified config file.

```
ha_url = "http://10.0.2.17:8123"
ha_key = 
dash_host = "10.0.2.17:3030"
dash_dir="/app/dashboards"
logfile = "/app/hapush/hapush.log"

##dash_dir = "/srv/hass/src/hadashboard/dashboards"
##logfile = "/etc/hapush/hapush.log"
```

**Comment by snizzleorg** [comment]
please try the following:

run on your host:

```
docker exec -t -i 0aac704f2093 /bin/bash
```

now you should be inside the container
then check if the config file is there

```
ls /app/hapush/
```

and also the dash(s)

```
ls /app/dashboards
```

you can get back to the host by typing `exit`

**Comment by xbmcnut** [comment]
Ooooh. Webpage is trying to load example file. Some progress...

```
2016-10-18 21:48:27,891 INFO Reading dashboard: /app/dashboards/main.erb
2016-10-18 21:48:27,948 INFO Reading dashboard: /app/dashboards/example.erb
```

**Comment by xbmcnut** [comment]
```
pi@raspberrypi:~ $ docker exec -t -i 0aac704f2093 /bin/bash
root@raspberrypi:/app# ls /app/hapush/
hapush.cfg  hapush.cfg.example  hapush.log  hapush.py
root@raspberrypi:/app# ls /app/dashboards
example.erb  layout.erb  main.erb
root@raspberrypi:/app#
```

**Comment by snizzleorg** [comment]
ok. so all there. is it running?

**Comment by xbmcnut** [comment]
Web page has loaded!! Very very slow but that is probably because I'm on a Pi1 model B! I did not want to mess with my live install before trying this so using on old hardware. I'll modify dash now to give me time/date and one switch status and go from there. I'll pop a blog post at http://xbmcnut.blogspot.com in the coming days outlining all the steps and debug info.

**Comment by snizzleorg** [comment]
Cool - Congrats. Its decently fast on a RPI2...

**Comment by xbmcnut** [comment]
Thank you so much for taking the time to help me get this going. Very much appreciated.

**Comment by xbmcnut** [comment]
I'll deploy on a Pi3 once I get it sorted. Using Imperihome with Vera2 now. Once my HA system goes online I'll need a replacement for my wall mounted phone that is wife and child friendly so this should do the trick nicely.

**Comment by snizzleorg** [comment]
you're welcome. Please link the blog post with the explanations once you got them maybe the Readme here would also need some more love...

**Comment by xbmcnut** [comment]
One more thing. I had to install docker on my Pi first using these steps which are forming the first part of my blog post. Are they correct?

`curl -sSL get.docker.com | sh`
If you would like to use Docker as a non-root user, you should now consider adding your user to the "docker" group with something like:
`sudo usermod -aG docker pi`
Set Docker to auto-start
`sudo systemctl enable docker`

If I can edit the ReadMe (never done that before), I can define all the steps required.

**Comment by snizzleorg** [comment]
I can't find the guide I used anymore but I guess the easiest way of getting docker to run on the Pi is this: http://blog.hypriot.com/getting-started-with-docker-on-your-arm-device/

To edit the read you need to fork this repo edit the read and than issue a pull request.

Or maybe get @acockburn (the maintainer) to incorporate your edits

**Comment by xbmcnut** [comment]
Will do, thanks. This is the docker guide I used http://blog.alexellis.io/getting-started-with-docker-on-raspberry-pi/

**Comment by xbmcnut** [comment]
How's this look? http://xbmcnut.blogspot.co.nz/2016/10/getting-hadashboard-up-and-running-on_19.html

**Comment by xbmcnut** [comment]
Stupid question, but does hadashboard allow you to interact with a device directly on HA? I've configured a switch and although hadashboard correctly reflects the status, clicking the icon turns the icon green but does nothing on HA.

**Comment by acockburn** [comment]
It certainly should - widgets are interactive where it makes sense.

**Comment by xbmcnut** [comment]
Thought as much otherwise it wouldn't be that useful. How would I debug that? Hapush log shows button interaction.

**Comment by acockburn** [comment]
What does thin.log show?

**Comment by xbmcnut** [comment]
Sorry, where is thin.log? Searched for it, couldn't find it.

```
2016-10-19 02:52:38,363 INFO Reading dashboard: /app/dashboards/main.erb
2016-10-19 02:52:38,416 INFO Reading dashboard: /app/dashboards/example.erb
2016-10-19 02:53:50,440 INFO switch.internal_led -> on
2016-10-19 02:53:54,424 INFO switch.internal_led -> off
2016-10-19 03:00:10,077 INFO switch.internal_led -> on
2016-10-19 03:00:15,433 INFO switch.internal_led -> off
```

**Comment by xbmcnut** [comment]
Oooh. This is in my HA log even though HA is working.

```
16-10-19 15:53:53 homeassistant.components.recorder: Error during query: (sqlite3.OperationalError) database is locked
16-10-19 15:53:59 homeassistant.components.recorder: Error during query: (sqlite3.OperationalError) database is locked
16-10-19 15:54:04 homeassistant.components.recorder: Error during query: (sqlite3.OperationalError) database is locked
```

**Comment by nickrout** [comment]
Thanks guys, this helped me learn a lot about docker and I now have mine going. (Yes XBMCNut, I do seem to be stalking you).

**Comment by TedX33** [comment]
XBMCNut, thanks for your blog, it helped me a bunch.  I got stuck on step 7 though with the following error:
`Unable to find image 'hadashboard:latest' locally
Pulling repository docker.io/library/hadashboard
docker: Error: image library/hadashboard:latest not found.
See 'docker run `--help'.``
I'm a fish out of water, I think I see what it's telling me, but I don't know how to correct it.
