### ISSUE TITLE
Moving docs to home-assistant.io

### ISSUE THREAD

**Issue by robbiet480** [acockburn/hadashboard#32]
Hi @acockburn,

We are about to add a new section to home-assistant.io titled "Ecosystem". It's a place where any external tools can share their documentation in an official and easy to reference capacity. I think that HADashboard would be a great fit. The PR to add this section should be merged tonight or tomorrow and docs can start being written shortly thereafter. I don't think you would need to do anything more than taking the existing README.md and splitting it up into pages for easy linking. 

Obviously you don't have to do this but we thought we'd let you know.

The PR that needs to be merged is [here](https://github.com/home-assistant/home-assistant.github.io/pull/1312).

Thanks!

**Comment by acockburn** [comment]
Happy to own the docs piece of this.

**Comment by robbiet480** [comment]
PR has been merged, add docs whenever you want!
