### ISSUE TITLE
LCARS integration for HADASHBOARD?

### ISSUE THREAD

**Issue by thundergreen** [acockburn/hadashboard#33]
Hey guzs. I was looking around for another nice theme for hadashboard and found this one : https://github.com/Aricwithana/LCARS-SDK 

Is it somehow possible to integrate this?

**Comment by acockburn** [comment]
It would be very cool to have an LCARS 'skin' for dashing but from what I can tell this would require a complete rewrite of the framework which is an immense amount of work that I am not prepared to do. Sorry.
