### ISSUE TITLE
Decimal portion of hasensor?

### ISSUE THREAD

**Issue by nickrout** [acockburn/hadashboard#34]
hasensor value is currently rounded to the nearest whole number. It would be nice to be able to specify the number of decimal points. For example the sabnzbd_speed sensor reports in MB/s and as my figure hovers around 1.5 to 4.0, it would be nice to have one decimal place. It reports one decimal place in the homeassistant web frontend.

Not a priority issue, more a suggestion.

**Comment by mikey60** [comment]
I agree it would be nice to get a decimal digit especially when monitoring a battery voltage.

**Comment by acockburn** [comment]
Will be fixed in AppDaemon v2
