### ISSUE TITLE
Link at the end of the readme is 404

### ISSUE THREAD

**Issue by nickrout** [acockburn/hadashboard#37]
The link at the end of the readme https://home-assistant.io/ecosystem/hadashboard is giving me a 404 at this point.

EDIT: I guess that this is related to #32 so I also guess this is a transitional problem. However it does leave people without ANY install docs for the moment. Cheers.

**Comment by acockburn** [comment]
Correct - I didn't expect the PR to take this long. If it goes on much longer I'll add the docs back in temporarily.
