### ISSUE TITLE
Background colors for all widgets?

### ISSUE THREAD

**Issue by jbardi** [acockburn/hadashboard#4]
Do you have any plans to add the bgcolor option for all widgets? The default gray is absolutely horrid and very hard on the eyes. I understand you like it, but man, that is the worst look ever.

Anyway, thanks for porting this over, its hard to operate HA from the standard web interface when using a wall mounted tablet, but this makes it a lot easier... just looking forward to being able to change the color.

Thanks! :)

**Comment by acockburn** [comment]
I disagree on your analysis of my wonderful gray background but I guess I can't please everyone ;) It is gray at least partly so it doesn't glow brightly at night.

But you are right, this would be a good addition so I'll take a look at how easy it would be to implement.

**Comment by acockburn** [comment]
OK, turns out it was pretty easy as I had already figured it out for the news widget. I will push a new release today or tomorrow with support for changing background color of all widgets.
