### ISSUE TITLE
Hagroup does not support all_devices

### ISSUE THREAD

**Issue by toddtigerpop** [acockburn/hadashboard#40]
Hello,  Would it be possible for Hagroup to not only compare on on/off, but also home/not_home?  This way it would work for all_devices as well.

Thanks.

**Comment by acockburn** [comment]
What would you want to do with this? Have it showing as on when all devices are home and off otherwise? Also, what would you expect pressing it to do? Maybe this would be better implemented as an extension of the presence widget?

**Comment by toddtigerpop** [comment]
Yes, that's mostly what I was thinking... I was thinking it would be more informational thank anything and didn't have an expectation for button presses.  I can look into the presence widget thing.  Thanks.

**Comment by acockburn** [comment]
DId the presence widget solve your problem?

**Comment by toddtigerpop** [comment]
Sorry, I haven't had a chance to try it out, been busy with other HA setups.  Will close this issue...  Thanks again for your help.
