### ISSUE TITLE
Max of 3 page navigation icons on additional pages

### ISSUE THREAD

**Issue by jbardi** [acockburn/hadashboard#6]
I am editing this issue as I fixed the problem I was having... it was a typing error on my part.

Thanks again for adding background colors for all tiles, now we just need sliders or up and down buttons for setting values like temperature on a thermostat and this will be a complete replacement for me!  I see a dimmer widget that you are working on, so hopefully there can be something for setting temperature in a similar way.

Thanks again!!! Awesome job!!!

**Comment by acockburn** [comment]
Thanks for the feedback - another member is working on a better dimmer widget. When we have that I think it will make an excellent basis for a slider as well.
